apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threat-intel-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/g-clef/ThreatIntelCollector.git
    targetRevision: master
    path:     argo-manifests/ti-collector/
  destination:
    server: https://kubernetes.default.svc
    namespace: ti-collector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m